#!/usr/bin/env python3
"""Build test/DemoExpect.mc from test/demo_ref.c's output.

Builds demo_ref.c against the original sources, plays DEMO1..3 with it
and turns the per-tic state lines into what test/DemoTest.mc checks:
a 16-bit hash of every tic's line (4 hex digits per tic, in one string)
and the full line every CHECKEVERY tics and at the last tic. From the
repo root:

    python3 test/gen_demo_expect.py [doom1.wad]

Never edit DemoExpect.mc by hand, rerun this.
"""

import os
import subprocess
import sys
import tempfile

D = os.path.expanduser("~/src/DOOM/linuxdoom-1.10")
CHECKEVERY = 250
FIELDS = ["tic", "x", "y", "z", "angle", "momx", "momy", "health", "armor",
          "readyweapon", "clip", "prndindex", "leveltime", "thinkers", "mobjs",
          "kills", "items", "secrets", "mobjhash", "sectorhash"]


def s32(v):
    v &= 0xFFFFFFFF
    return v - (1 << 32) if v >= (1 << 31) else v


def line_hash(fields):
    # rotate left 5 and xor, like mix() in demo_ref.c, folded to 16 bits
    h = 0
    for v in fields:
        h = (((h << 5) | (h >> 27)) & 0xFFFFFFFF) ^ (v & 0xFFFFFFFF)
    return (h ^ (h >> 16)) & 0xFFFF


def main():
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
    wad = sys.argv[1] if len(sys.argv) > 1 else os.path.join(root, "doom1.wad")
    with tempfile.TemporaryDirectory() as tmp:
        exe = os.path.join(tmp, "demo_ref")
        srcs = sorted(f"{D}/{f}" for f in os.listdir(D) if f.startswith("p_") and f.endswith(".c") and f != "p_saveg.c")
        subprocess.check_call(["gcc", "-w", "-I", D, os.path.join(root, "test", "demo_ref.c")] + srcs
                              + [f"{D}/{f}" for f in ("d_items.c", "info.c", "tables.c", "m_random.c", "m_bbox.c")]
                              + ["-o", exe])
        out = ["// Generated by test/gen_demo_expect.py from test/demo_ref.c's output, do not edit.",
               "",
               "import Toybox.Lang;",
               "",
               "(:test)",
               "module DemoExpect {",
               "",
               "    // per tic line: " + ", ".join(FIELDS),
               f"    const CHECKEVERY = {CHECKEVERY};"]
        for n in (1, 2, 3):
            text = subprocess.check_output([exe, wad, f"DEMO{n}"], text=True)
            lines = [[int(v) for v in l.split()] for l in text.splitlines()]
            assert all(len(l) == len(FIELDS) for l in lines)
            hashes = "".join(f"{line_hash(l):04x}" for l in lines)
            checks = [l for l in lines if l[0] % CHECKEVERY == CHECKEVERY - 1 or l is lines[-1]]
            out.append("")
            out.append(f"    // DEMO{n}: {len(lines)} tics")
            out.append(f"    const DEMO{n}_TICS = {len(lines)};")
            out.append(f"    function demo{n}Hashes() as String {{")
            out.append(f'        return "{hashes}";')
            out.append("    }")
            out.append(f"    // the full line after tic {CHECKEVERY - 1}, {2 * CHECKEVERY - 1}, ... and the last")
            out.append(f"    function demo{n}Checks() as Array<Array<Number>> {{")
            out.append("        return [")
            out.append(",\n".join("            [" + ", ".join(str(v) for v in l) + "]" for l in checks))
            out.append("        ] as Array<Array<Number>>;")
            out.append("    }")
            print(f"DEMO{n}: {len(lines)} tics, {len(checks)} checkpoints", file=sys.stderr)
        out.append("}")
    with open(os.path.join(root, "test", "DemoExpect.mc"), "w") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
